### PR TITLE
Added import of Private Tags

### PR DESCRIPTION
**Pull request by IanSimpson**
This commit adds Private Tags to the list of items imported by the
plugin.

It also adds a new PublicationTagHailList class, allowing filtering of
Publications by Private Tags

### CODE REVIEW

**Comment by IanSimpson** [comment]
Hold the line. Chasing down a bug still.

**Comment by IanSimpson** [comment]
Not sure where the issue lies, but suspect something still isn't quite right here. My Private Tags imported as (regular) Tags. Deleting and re-importing seemed to work. Possibly caused by importing Articles/Publications BEFORE Tags (which auto-creates them), which is worked around in my last commit anyway.

**Comment by IanSimpson** [comment]
And bug fixed. Split the HailTag class in a more logical manner, order is restored in the world.

**Comment by marc-firebrand** [comment]
Closing this since version 4 now integrates this functionality in core.

**Pull request closed without merging**
